import os
import json
import re
import pandas as pd


# ─────────────────────────────────────────────────────
# Padrões narrativos — menções ao Spotify que NÃO são Call2Go
# Ex.: "200 dias nos charts do Spotify" é branding, não CTA
# ─────────────────────────────────────────────────────
_NARRATIVE_PATTERNS = [
    r'chart\w*\s+(?:do|no|da|dos|nos)\s+spotify',
    r'ranking\s+(?:do|no|da)\s+spotify',
    r'top\s+\d+\s+(?:do|no)\s+spotify',
    r'milh[ãõ]\w*\s+(?:de\s+)?(?:plays?|streams?|reprodu[çc][ãõ])\w*\s+(?:no|do)\s+spotify',
    r'\d+\s+dias?\s+(?:no|nos)\s+chart',
    r'#\d+\s+(?:no|do)\s+spotify',
]


def _is_narrative_mention(text_lower):
    """Verifica se a menção ao Spotify é contexto narrativo, não Call2Go."""
    return any(re.search(p, text_lower) for p in _NARRATIVE_PATTERNS)


def is_auto_generated(description):
    """
    Detecta se um vídeo é auto-gerado pelo YouTube (Content ID / OAC).
    Esses vídeos são criados automaticamente por labels/distribuidoras, não pelo artista.
    Padrão: "Provided to YouTube by <distribuidora>" na primeira linha.

    Returns:
        bool
    """
    if not isinstance(description, str) or not description.strip():
        return False
    first_line = description.strip().split('\n')[0].lower()
    return first_line.startswith('provided to youtube by') or \
        first_line.startswith('auto-generated by youtube')


def detect_call2go(text):
    """
    Analisa o texto via Expressões Regulares para detectar a estratégia Call2Go.
    Retorna: (has_call2go, call_type)
    """
    if not isinstance(text, str):
        return 0, 'nenhum'

    # Padroniza o texto para minúsculas para facilitar o matching
    text_lower = text.lower()

    # 1. Busca por Link Direto (Spoti.fi, sptfy.com ou open.spotify.com)
    link_pattern = r'(https?://(?:open\.spotify\.com|spoti\.fi|sptfy\.com)[^\s]+)'
    if re.search(link_pattern, text_lower):
        return 1, 'link_direto'

    # 1b. Spotify redirect links (lnk.to, bit.ly, smarturl.it, etc.)
    # Padrão: "Spotify" + separador (: | - –) + URL na mesma linha
    if re.search(r'spotify\s*[:\|\-\u2013]\s*https?://[^\s]+', text_lower):
        return 1, 'link_direto'

    # 1c. URLs que contêm 'spotify' ou 'sptfy' no caminho (serviços de redirect)
    # Ex: bit.ly/LivinhoNoSpotify, smarturl.it/mj_otw_sptfy
    if re.search(r'https?://[^\s]*(?:spotify|sptfy)[^\s]*', text_lower):
        return 1, 'link_direto'

    # 2. Busca por Texto Implícito (Semântica)
    # Padrões que indicam direcionamento de plataforma
    # Permite palavras entre o verbo e "spotify" (ex: "Ouça MC Livinho no Spotify")
    implicit_patterns = [
        r'ou[çc]a\b.{0,50}\bspotify',
        r'dispon[ií]vel\b.{0,30}\bspotify',
        r'\bstream\b.{0,50}\bspotify',
        r'\bouvir\b.{0,50}\bspotify',
    ]

    for pattern in implicit_patterns:
        if re.search(pattern, text_lower):
            return 1, 'texto_implicito'

    # Fallback: menção isolada ao Spotify — mas só se NÃO for narrativa
    # "200 dias nos charts do Spotify" = narrativa, não Call2Go
    if re.search(r'\bspotify\b', text_lower) and not _is_narrative_mention(text_lower):
        return 1, 'texto_implicito'

    return 0, 'nenhum'


def detect_call2go_channel(channel_description):
    """
    Analisa a descrição do PERFIL DO CANAL do YouTube.
    Detecta se o artista coloca link/referência ao Spotify na bio do canal.
    Retorna: (has_call2go_channel, channel_call2go_type)
    """
    if not isinstance(channel_description, str) or not channel_description.strip():
        return 0, 'nenhum'

    text_lower = channel_description.lower()

    # Link direto na bio do canal (spoti.fi, sptfy.com ou open.spotify.com)
    link_pattern = r'(https?://(?:open\.spotify\.com|spoti\.fi|sptfy\.com)[^\s]+)'
    if re.search(link_pattern, text_lower):
        return 1, 'link_direto'

    # Spotify redirect links na bio do canal
    if re.search(r'spotify\s*[:\|\-\u2013]\s*https?://[^\s]+', text_lower):
        return 1, 'link_direto'

    # URLs com spotify/sptfy no caminho
    if re.search(r'https?://[^\s]*(?:spotify|sptfy)[^\s]*', text_lower):
        return 1, 'link_direto'

    # Texto implícito na bio do canal
    # NÃO usa \bspotify\b como fallback — bios têm menção narrativa
    # Range limitado (.{0,50}) para evitar match cross-sentence
    implicit_patterns = [
        r'ou[çc]a\b.{0,50}\bspotify',
        r'dispon[ií]vel\b.{0,30}\bspotify',
        r'\bstream\b.{0,50}\bspotify',
        r'\bouvir\b.{0,50}\bspotify',
    ]

    for pattern in implicit_patterns:
        if re.search(pattern, text_lower):
            return 1, 'texto_implicito'

    return 0, 'nenhum'


def detect_call2go_channel_scraped(channel_id, scraped_data):
    """
    Detecta Call2Go via links estruturados scrapeados da aba Sobre do canal.

    Usa os dados de channel_link_scraper.py (web scraping) que captura
    os botões de redes sociais que a YouTube Data API não expõe.

    Para canais OAC (auto-gerados), também verifica links do canal oficial
    descoberto automaticamente pelo scraper.

    Args:
        channel_id: ID do canal do YouTube
        scraped_data: dict carregado de channel_links_scraped.json

    Returns:
        (has_call2go, type): (1, 'link_direto') se tem link do Spotify, senão (0, 'nenhum')
    """
    if not scraped_data or channel_id not in scraped_data:
        return 0, 'nenhum'

    channel_info = scraped_data[channel_id]

    # Verifica links diretos do canal
    if channel_info.get('has_spotify') and channel_info.get('spotify_links'):
        return 1, 'link_direto'

    # Para OAC: verifica links do canal oficial (mesclados pelo scraper)
    if channel_info.get('official_spotify_links'):
        return 1, 'link_direto'

    # Para OAC: verifica canal oficial no cache (se o scraper salvou separadamente)
    official_id = channel_info.get('official_channel_id')
    if official_id and official_id in scraped_data:
        official_info = scraped_data[official_id]
        if official_info.get('has_spotify') and official_info.get('spotify_links'):
            return 1, 'link_direto'

    return 0, 'nenhum'


def process_videos():
    print("Iniciando Pipeline de Detecção NLP para Call2Go...")

    # Caminhos relativos à raiz do projeto
    input_file = "data/raw/youtube_videos_raw.jsonl"
    output_file = "data/processed/youtube_call2go_flagged.csv"
    scraped_file = "data/raw/channel_links_scraped.json"

    if not os.path.exists(input_file):
        print(
            f"[ERRO] Arquivo bruto não encontrado em {input_file}. Rode os coletores primeiro.")
        return

    # Carrega links scrapeados dos canais (se existir)
    scraped_data = {}
    if os.path.exists(scraped_file):
        with open(scraped_file, 'r', encoding='utf-8') as f:
            scraped_data = json.load(f)
        print(
            f"  Links scrapeados dos canais carregados: {len(scraped_data)} canais")

    # Carrega mapeamento artist_name → seed channel_id (para resolver mismatches)
    seed_file = "data/seed/artistas.csv"
    seed_channels = {}
    if os.path.exists(seed_file):
        df_seed = pd.read_csv(seed_file)
        if 'youtube_channel_id' in df_seed.columns:
            seed_channels = dict(
                zip(df_seed['artist_name'], df_seed['youtube_channel_id']))

    processed_data = []

    # Leitura otimizada de JSONL (linha por linha, não sobrecarrega a RAM)
    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            video = json.loads(line)

            description = video.get('description', '')
            channel_id = video.get('channel_id', '')

            # Flag: vídeo auto-gerado (Provided to YouTube by...)
            auto_gen = is_auto_generated(description)

            # Nível 1: Detecta Call2Go na descrição do VÍDEO
            has_call2go, call_type = detect_call2go(description)

            # Nível 2: Links estruturados scrapeados da aba Sobre (About page)
            # Tenta pelo channel_id do vídeo E pelo channel_id do seed (podem divergir)
            has_scraped, scraped_type = detect_call2go_channel_scraped(
                channel_id, scraped_data)

            # Fallback: tenta pelo channel_id do seed (resolve mismatches de canal)
            artist_name = video.get('artist_name', '')
            if not has_scraped and artist_name in seed_channels:
                seed_ch = seed_channels[artist_name]
                if seed_ch != channel_id:
                    has_scraped, scraped_type = detect_call2go_channel_scraped(
                        seed_ch, scraped_data)

            # Canal: apenas links estruturados
            final_channel_has = has_scraped
            final_channel_type = scraped_type if has_scraped else 'nenhum'

            # Classificação combinada: vídeo prevalece, canal complementa
            combined_has = has_call2go or final_channel_has
            if has_call2go and final_channel_has:
                # Ambas as fontes têm Call2Go — usa o tipo mais forte
                type_priority = {'link_direto': 2,
                                 'texto_implicito': 1, 'nenhum': 0}
                combined_type = call_type if type_priority.get(call_type, 0) >= type_priority.get(
                    final_channel_type, 0) else final_channel_type
                combined_source = 'ambos'
            elif has_call2go:
                combined_type = call_type
                combined_source = 'video'
            elif final_channel_has:
                combined_type = final_channel_type
                combined_source = 'canal'
            else:
                combined_type = 'nenhum'
                combined_source = 'nenhum'

            # OAC flag do canal
            is_oac = False
            if scraped_data and channel_id in scraped_data:
                is_oac = scraped_data[channel_id].get(
                    'is_auto_generated_channel', False)

            # Mapeia as colunas extraindo apenas o necessário para a Análise Estatística
            processed_data.append({
                'video_id': video.get('video_id'),
                'artist_name': video.get('artist_name'),
                'title': video.get('title'),
                'published_at': video.get('published_at'),
                'view_count': video.get('view_count'),
                'like_count': video.get('like_count'),
                'comment_count': video.get('comment_count'),
                'has_call2go': int(combined_has),
                'call2go_type': combined_type,
                'call2go_source': combined_source,
                'video_call2go': call_type,
                'channel_call2go': final_channel_type,
                'is_auto_generated': int(auto_gen),
                'is_oac_channel': int(is_oac),
            })

    # Converte para DataFrame do Pandas para sumarização e exportação
    df = pd.DataFrame(processed_data)

    # Garante que a pasta de destino exista
    os.makedirs("data/processed", exist_ok=True)

    # Salva o dataset limpo e enriquecido
    df.to_csv(output_file, index=False, encoding='utf-8')
    print(f"✅ Processamento concluído. {len(df)} vídeos analisados.")

    # Resumo por tipo combinado
    print(f"\n--- DISTRIBUIÇÃO COMBINADA (Vídeo + Canal) ---")
    for ctype, count in df['call2go_type'].value_counts().items():
        pct = count / len(df) * 100
        print(f"  {ctype}: {count} ({pct:.1f}%)")

    # Resumo por fonte
    print(f"\n--- FONTE DA DETECÇÃO ---")
    for source, count in df['call2go_source'].value_counts().items():
        pct = count / len(df) * 100
        print(f"  {source}: {count} ({pct:.1f}%)")

    # Resumo de qualidade dos dados
    auto_gen_count = df['is_auto_generated'].sum()
    oac_count = df['is_oac_channel'].sum()
    print(f"\n--- QUALIDADE DOS DADOS ---")
    print(
        f"  Vídeos auto-gerados:  {auto_gen_count} ({auto_gen_count/len(df)*100:.1f}%)")
    print(
        f"  Canais OAC:           {oac_count} ({oac_count/len(df)*100:.1f}%)")
    print(f"  Vídeos orgânicos:     {len(df) - auto_gen_count}")

    return df


if __name__ == "__main__":
    process_videos()
