"""Detector regex para estrategia Call2Go (cross-platform YouTube -> Spotify).

Instrumento de mensuracao do TCC -- nao e o objeto de estudo.
Validacao definitiva (Fase 8, 10/04/2026, 91 videos adversariais, anotacao cega):
- Kappa video: 0.45 (moderado), acuracia 82.4%
- Kappa canal: 0.80 (substancial), acuracia 90.1%

Os padroes regex sao compilados uma unica vez em tempo de import (module-level)
para evitar recompilacao por chamada em loops sobre milhares de videos.
"""

import os
import json
import re
import pandas as pd


# ─────────────────────────────────────────────────────
# Padroes compilados (module-level) -- evita recompilacao por chamada
# ─────────────────────────────────────────────────────

# Padroes narrativos: mencoes ao Spotify que NAO sao Call2Go
# Ex.: "200 dias nos charts do Spotify" e branding, nao CTA
_NARRATIVE_PATTERNS = [
    re.compile(r'chart\w*\s+(?:do|no|da|dos|nos)\s+spotify'),
    re.compile(r'ranking\s+(?:do|no|da)\s+spotify'),
    re.compile(r'top\s+\d+\s+(?:do|no)\s+spotify'),
    re.compile(r'milh[ãõ]\w*\s+(?:de\s+)?(?:plays?|streams?|reprodu[çc][ãõ])\w*\s+(?:no|do)\s+spotify'),
    re.compile(r'\d+\s+dias?\s+(?:no|nos)\s+chart'),
    re.compile(r'#\d+\s+(?:no|do)\s+spotify'),
]

# R1: Link direto a dominios oficiais do Spotify
_R1_DIRECT_LINK = re.compile(
    r'(https?://(?:open\.spotify\.com|spoti\.fi|sptfy\.com)[^\s]+)'
)

# R2: "Spotify" + separador + URL (redirect rotulado)
_R2_LABELED_REDIRECT = re.compile(
    r'spotify\s*[:\|\-–]\s*https?://[^\s]+'
)

# R3: URLs com 'spotify' ou 'sptfy' no path (bit.ly/spotify-..., smarturl.it/sptfy_...)
_R3_PATH_REDIRECT = re.compile(
    r'https?://[^\s]*(?:spotify|sptfy)[^\s]*'
)

# R4: CTAs textuais com "Spotify" proximo (com palavras intermedias permitidas)
# Range maior (50ch) para video; menor (30ch) para "disponivel" (mais especifico)
_R4_IMPLICIT_PATTERNS = [
    re.compile(r'ou[çc]a\b.{0,50}\bspotify'),
    re.compile(r'dispon[ií]vel\b.{0,30}\bspotify'),
    re.compile(r'\bstream\b.{0,50}\bspotify'),
    re.compile(r'\bouvir\b.{0,50}\bspotify'),
]

# R5: mencao isolada a "spotify" -- ALTO risco de FP, so usar apos guard narrativo
_R5_FALLBACK_SPOTIFY = re.compile(r'\bspotify\b')

# Heuristica auto-generated YouTube (Content ID / OAC)
_AUTO_GEN_PREFIXES = ('provided to youtube by', 'auto-generated by youtube')

# Prioridade de tipos para resolucao em modo combinado AND
_TYPE_PRIORITY = {'link_direto': 2, 'texto_implicito': 1, 'nenhum': 0}


# ─────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────

def _is_narrative_mention(text_lower):
    """Verifica se a mencao ao Spotify e contexto narrativo, nao Call2Go."""
    return any(p.search(text_lower) for p in _NARRATIVE_PATTERNS)


def _check_direct_link(text_lower):
    """R1+R2+R3: links diretos a Spotify ou redirects rotulados."""
    if _R1_DIRECT_LINK.search(text_lower):
        return True
    if _R2_LABELED_REDIRECT.search(text_lower):
        return True
    if _R3_PATH_REDIRECT.search(text_lower):
        return True
    return False


def _check_implicit_cta(text_lower):
    """R4: CTAs textuais (ouca/disponivel/stream/ouvir + spotify)."""
    return any(p.search(text_lower) for p in _R4_IMPLICIT_PATTERNS)


def is_auto_generated(description):
    """
    Detecta se um video e auto-gerado pelo YouTube (Content ID / OAC).
    Esses videos sao criados automaticamente por labels/distribuidoras, nao pelo artista.
    Padrao: "Provided to YouTube by <distribuidora>" na primeira linha.

    Returns:
        bool
    """
    if not isinstance(description, str) or not description.strip():
        return False
    first_line = description.strip().split('\n')[0].lower()
    return first_line.startswith(_AUTO_GEN_PREFIXES)


# ─────────────────────────────────────────────────────
# Detectores publicos
# ─────────────────────────────────────────────────────

def detect_call2go(text):
    """
    Analisa o texto via Expressoes Regulares para detectar a estrategia Call2Go.
    Aplicado a descricao de VIDEO (com fallback R5 + guard narrativo).

    Returns:
        (has_call2go, call_type) onde call_type in {'link_direto', 'texto_implicito', 'nenhum'}
    """
    if not isinstance(text, str):
        return 0, 'nenhum'

    text_lower = text.lower()

    if _check_direct_link(text_lower):
        return 1, 'link_direto'

    if _check_implicit_cta(text_lower):
        return 1, 'texto_implicito'

    # R5 (fallback): mencao isolada -- so se NAO for narrativa
    # "200 dias nos charts do Spotify" = narrativa, nao Call2Go
    if _R5_FALLBACK_SPOTIFY.search(text_lower) and not _is_narrative_mention(text_lower):
        return 1, 'texto_implicito'

    return 0, 'nenhum'


def detect_call2go_channel(channel_description):
    """
    Analisa a descricao do PERFIL DO CANAL do YouTube.
    Detecta se o artista coloca link/referencia ao Spotify na bio do canal.

    Diferenca crucial vs detect_call2go (video):
    - NAO usa o fallback R5 (\\bspotify\\b) -- bios costumam ter mencao narrativa
      (ex.: "ouca minhas musicas no Spotify e em todos os apps") que aqui seria FP.

    Returns:
        (has_call2go_channel, channel_call2go_type)
    """
    if not isinstance(channel_description, str) or not channel_description.strip():
        return 0, 'nenhum'

    text_lower = channel_description.lower()

    if _check_direct_link(text_lower):
        return 1, 'link_direto'

    if _check_implicit_cta(text_lower):
        return 1, 'texto_implicito'

    return 0, 'nenhum'


def detect_call2go_channel_scraped(channel_id, scraped_data):
    """
    Detecta Call2Go via links estruturados scrapeados da aba Sobre do canal.

    Usa os dados de channel_link_scraper.py (web scraping) que captura
    os botoes de redes sociais que a YouTube Data API nao expoe.

    Para canais OAC (auto-gerados), tambem verifica links do canal oficial
    descoberto automaticamente pelo scraper.

    Args:
        channel_id: ID do canal do YouTube
        scraped_data: dict carregado de channel_links_scraped.json

    Returns:
        (has_call2go, type): (1, 'link_direto') se tem link do Spotify, senao (0, 'nenhum')
    """
    if not scraped_data or channel_id not in scraped_data:
        return 0, 'nenhum'

    channel_info = scraped_data[channel_id]

    if channel_info.get('has_spotify') and channel_info.get('spotify_links'):
        return 1, 'link_direto'

    if channel_info.get('official_spotify_links'):
        return 1, 'link_direto'

    official_id = channel_info.get('official_channel_id')
    if official_id and official_id in scraped_data:
        official_info = scraped_data[official_id]
        if official_info.get('has_spotify') and official_info.get('spotify_links'):
            return 1, 'link_direto'

    return 0, 'nenhum'


# ─────────────────────────────────────────────────────
# Resolucao combinada video + canal
# ─────────────────────────────────────────────────────

def _resolve_combined(video_type, channel_type, video_has, channel_has):
    """Logica combinada AND (ambos) e tipo dominante por prioridade."""
    if video_has and channel_has:
        if _TYPE_PRIORITY.get(video_type, 0) >= _TYPE_PRIORITY.get(channel_type, 0):
            return video_type, 'ambos'
        return channel_type, 'ambos'
    return 'nenhum', 'nenhum'


def _resolve_channel_detection(seed_ch, channel_id, scraped_data, channel_description):
    """
    Determina has_channel + tipo combinando: scraped (seed) -> scraped (jsonl) -> regex bio.

    Ordem de fallback preserva o comportamento original do detector.
    """
    if seed_ch:
        has_scraped, scraped_type = detect_call2go_channel_scraped(seed_ch, scraped_data)
    else:
        has_scraped, scraped_type = detect_call2go_channel_scraped(channel_id, scraped_data)

    if not has_scraped and channel_id and channel_id != seed_ch:
        has_scraped, scraped_type = detect_call2go_channel_scraped(channel_id, scraped_data)

    if has_scraped:
        return has_scraped, scraped_type

    # Fallback final: regex na bio do canal (bit.ly rotulado etc.)
    bio_has, bio_type = detect_call2go_channel(channel_description or '')
    if bio_has:
        return bio_has, bio_type

    return 0, 'nenhum'


# ─────────────────────────────────────────────────────
# Pipeline (step 6)
# ─────────────────────────────────────────────────────

def process_videos():
    print("Iniciando Pipeline de Deteccao NLP para Call2Go...")

    input_file = "data/raw/youtube_videos_raw.jsonl"
    output_file = "data/processed/youtube_call2go_flagged.csv"
    scraped_file = "data/raw/channel_links_scraped.json"

    if not os.path.exists(input_file):
        print(
            f"[ERRO] Arquivo bruto nao encontrado em {input_file}. Rode os coletores primeiro.")
        return

    scraped_data = {}
    if os.path.exists(scraped_file):
        with open(scraped_file, 'r', encoding='utf-8') as f:
            scraped_data = json.load(f)
        print(f"  Links scrapeados dos canais carregados: {len(scraped_data)} canais")

    # Mapeamento artist_name -> seed channel_id (resolve mismatches video<->seed)
    seed_file = "data/seed/artistas.csv"
    seed_channels = {}
    if os.path.exists(seed_file):
        df_seed = pd.read_csv(seed_file)
        if 'youtube_channel_id' in df_seed.columns:
            seed_channels = dict(
                zip(df_seed['artist_name'], df_seed['youtube_channel_id']))

    processed_data = []

    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            video = json.loads(line)

            description = video.get('description', '')
            channel_id = video.get('channel_id', '')
            artist_name = video.get('artist_name', '')
            channel_desc = video.get('channel_description', '') or ''

            auto_gen = is_auto_generated(description)
            has_video, video_type = detect_call2go(description)

            seed_ch = seed_channels.get(artist_name, '')
            has_channel, channel_type = _resolve_channel_detection(
                seed_ch, channel_id, scraped_data, channel_desc)

            or_has = has_video or has_channel
            combined_has = has_video and has_channel
            combined_type, combined_source = _resolve_combined(
                video_type, channel_type, has_video, has_channel)

            is_oac = bool(scraped_data.get(channel_id, {}).get(
                'is_auto_generated_channel', False))

            processed_data.append({
                'video_id': video.get('video_id'),
                'artist_name': artist_name,
                'title': video.get('title'),
                'published_at': video.get('published_at'),
                'view_count': video.get('view_count'),
                'like_count': video.get('like_count'),
                'comment_count': video.get('comment_count'),
                'has_call2go': int(combined_has),
                'has_call2go_or': int(or_has),
                'call2go_type': combined_type,
                'call2go_source': combined_source,
                'video_call2go': video_type,
                'channel_call2go': channel_type,
                'is_auto_generated': int(auto_gen),
                'is_oac_channel': int(is_oac),
            })

    df = pd.DataFrame(processed_data)
    os.makedirs("data/processed", exist_ok=True)
    df.to_csv(output_file, index=False, encoding='utf-8')
    print(f"[OK] Processamento concluido. {len(df)} videos analisados.")

    print(f"\n--- DISTRIBUICAO COMBINADA/AND (Video E Canal) ---")
    for ctype, count in df['call2go_type'].value_counts().items():
        pct = count / len(df) * 100
        print(f"  {ctype}: {count} ({pct:.1f}%)")

    or_count = df['has_call2go_or'].sum()
    print(f"\n--- LOGICA OR (Video OU Canal) ---")
    print(f"  has_call2go_or = 1: {or_count} ({or_count/len(df)*100:.1f}%)")
    print(f"  has_call2go_or = 0: {len(df) - or_count} ({(len(df)-or_count)/len(df)*100:.1f}%)")

    print(f"\n--- FONTE DA DETECCAO ---")
    for source, count in df['call2go_source'].value_counts().items():
        pct = count / len(df) * 100
        print(f"  {source}: {count} ({pct:.1f}%)")

    auto_gen_count = df['is_auto_generated'].sum()
    oac_count = df['is_oac_channel'].sum()
    print(f"\n--- QUALIDADE DOS DADOS ---")
    print(f"  Videos auto-gerados:  {auto_gen_count} ({auto_gen_count/len(df)*100:.1f}%)")
    print(f"  Canais OAC:           {oac_count} ({oac_count/len(df)*100:.1f}%)")
    print(f"  Videos organicos:     {len(df) - auto_gen_count}")

    return df


if __name__ == "__main__":
    process_videos()
