"""
Scraper para capturar links estruturados da aba Sobre (About) de canais do YouTube.

A YouTube Data API v3 NÃO expõe os links estruturados que aparecem na aba Sobre
do canal (aqueles botões de Instagram, Spotify, TikTok, etc.). Esses links só
existem no HTML da página.

Este módulo faz web scraping de DUAS páginas por canal:
1. Página principal do canal — captura links do ytInitialData
2. Página /about — captura channelExternalLinkViewModel (links estruturados)

Também detecta se o canal é auto-gerado pelo YouTube (OAC) — esses canais
não têm links personalizados e seus vídeos são "Provided to YouTube by..."

Saída: data/raw/channel_links_scraped.json
"""
import os
import re
import json
import time
import requests
from urllib.parse import unquote


_HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    'Accept-Language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
}

_SPOTIFY_DOMAINS = ['open.spotify.com', 'spoti.fi',
                    'sptfy.com', 'spotify.com', 'spotify.link']

_INTERNAL_DOMAINS = [
    'youtube.com', 'ytimg.com', 'googlevideo.com',
    'googleadservices.com', 'google.com', 'gstatic.com',
    'googleapis.com', 'ggpht.com', 'youtube-nocookie.com',
    'googleusercontent.com', 'schema.org',
]


def _extract_urls_from_text(text):
    """Extrai todos os URLs de um bloco de texto, decodificando redirects."""
    # Unescape JSON unicode sequences que quebram a extração de URLs
    # YouTube usa \u0026 para & no JSON, o que impede capturar ?q= dos redirects
    text = text.replace('\\u0026', '&')
    text = text.replace('\\u003d', '=')
    text = text.replace('\\u003c', '<')
    text = text.replace('\\u003e', '>')
    text = text.replace('\\u002F', '/')
    text = text.replace('\\u002f', '/')

    urls = []
    seen = set()

    for match in re.finditer(r'https?://[^\s"\\<>{}|^`\[\]]+', text):
        u = match.group(0)

        # Decodifica YouTube redirects
        if 'youtube.com/redirect' in u and 'q=' in u:
            q_match = re.search(r'[?&]q=([^&"]+)', u)
            if q_match:
                u = unquote(q_match.group(1))

        # Decodifica URL-encoded
        if '%3A%2F%2F' in u:
            u = unquote(u)

        u = u.rstrip('.,;:)]}')

        # Filtra internas
        if any(d in u.lower() for d in _INTERNAL_DOMAINS):
            continue
        if u in seen or len(u) < 10:
            continue

        seen.add(u)
        urls.append(u)

    return urls


def _is_spotify_url(url):
    """Verifica se um URL é do Spotify."""
    return any(d in url.lower() for d in _SPOTIFY_DOMAINS)


def scrape_channel_links(channel_id, session=None):
    """
    Acessa a página do canal + /about no YouTube e extrai links.

    Estratégia em 2 fases:
        Fase 1: Página principal — extrai ytInitialData para links gerais
        Fase 2: Página /about — extrai channelExternalLinkViewModel para links
                 estruturados da aba Sobre (botões de redes sociais)

    Também detecta se o canal é auto-gerado (OAC).

    Returns:
        dict com 'links', 'spotify_links', 'has_spotify', 'is_auto_generated_channel'
    """
    if session is None:
        session = requests.Session()

    all_links = []
    spotify_links = []
    is_oac = False

    # Fase 1: Página principal do canal
    try:
        resp = session.get(
            f"https://www.youtube.com/channel/{channel_id}",
            headers=_HEADERS, timeout=15
        )
        resp.raise_for_status()
        html_main = resp.text

        yt_match = re.search(
            r'(?:var\s+)?ytInitialData\s*=\s*({.*?})\s*;\s*</script>',
            html_main, re.DOTALL
        )
        if yt_match:
            all_links.extend(_extract_urls_from_text(yt_match.group(1)))

    except requests.RequestException as e:
        print(f"  [ERRO] Página principal {channel_id}: {e}")
        return {
            'links': [], 'spotify_links': [], 'has_spotify': False,
            'is_auto_generated_channel': False, 'error': str(e)
        }

    # Fase 2: Página /about (links estruturados)
    try:
        time.sleep(0.5)  # delay entre requests ao mesmo canal
        resp_about = session.get(
            f"https://www.youtube.com/channel/{channel_id}/about",
            headers=_HEADERS, timeout=15
        )
        resp_about.raise_for_status()
        html_about = resp_about.text

        # Detecta canal auto-gerado (OAC)
        if 'Gerado automaticamente pelo YouTube' in html_about or 'Auto-generated by YouTube' in html_about:
            is_oac = True

        # Extrai channelExternalLinkViewModel — links estruturados
        yt_about_match = re.search(
            r'(?:var\s+)?ytInitialData\s*=\s*({.*?})\s*;\s*</script>',
            html_about, re.DOTALL
        )
        if yt_about_match:
            about_data = yt_about_match.group(1)

            # Busca todos os URLs do about data inteiro (inclui redirect URLs)
            # Important: fazemos no about_data completo para pegar URLs de redirect
            # com q= que contêm as URLs reais dos links estruturados
            about_urls = _extract_urls_from_text(about_data)
            all_links.extend(about_urls)

        # Fallback: busca direta no HTML por URLs do Spotify
        spotify_html = re.findall(
            r'(https?://(?:open\.spotify\.com|spoti\.fi|sptfy\.com|spotify\.link)[^\s"\\<>]*)',
            html_about, re.IGNORECASE
        )
        for link in spotify_html:
            clean = link.rstrip('.,;:)')
            if clean not in all_links:
                all_links.append(clean)

    except requests.RequestException as e:
        print(f"  [AVISO] Página /about {channel_id}: {e}")

    # Deduplica e classifica
    seen = set()
    unique_links = []
    for u in all_links:
        if u not in seen:
            seen.add(u)
            unique_links.append(u)
            if _is_spotify_url(u):
                spotify_links.append(u)

    return {
        'links': unique_links,
        'spotify_links': spotify_links,
        'has_spotify': len(spotify_links) > 0,
        'is_auto_generated_channel': is_oac,
    }


def scrape_all_channels(artists_channels, output_file="data/raw/channel_links_scraped.json",
                        delay=2.0, force=False):
    """
    Faz scraping de todos os canais dos artistas.

    Args:
        artists_channels: dict {artist_name: channel_id}
        output_file: caminho para salvar o cache JSON
        delay: segundos entre requests (respeita rate limiting)
        force: se True, ignora cache e re-scrapa todos
    """
    print("=" * 60)
    print("SCRAPING DE LINKS ESTRUTURADOS DOS CANAIS DO YOUTUBE")
    print("(Página principal + /about para cada canal)")
    print("=" * 60)

    cache = {}
    if not force and os.path.exists(output_file):
        with open(output_file, 'r', encoding='utf-8') as f:
            cache = json.load(f)
        print(
            f"  Cache existente: {len(cache)} canais (use --force para re-scraper)")

    session = requests.Session()
    total = len(artists_channels)
    scraped = 0
    spotify_found = 0
    oac_count = 0

    for i, (artist, channel_id) in enumerate(artists_channels.items()):
        # Usa cache se já existe e não tem erro
        if not force and channel_id in cache and 'error' not in cache[channel_id]:
            result = cache[channel_id]
            oac_tag = " [OAC]" if result.get(
                'is_auto_generated_channel') else ""
            spotify_tag = "Spotify SIM" if result['has_spotify'] else "sem Spotify"
            print(f"  [{i+1}/{total}] {artist}: CACHE ({spotify_tag}{oac_tag})")
            if result['has_spotify']:
                spotify_found += 1
            if result.get('is_auto_generated_channel'):
                oac_count += 1
            continue

        print(f"  [{i+1}/{total}] Scraping: {artist} ({channel_id})...", end=' ')

        result = scrape_channel_links(channel_id, session)
        result['artist_name'] = artist
        cache[channel_id] = result

        oac_tag = " [OAC - AUTO-GERADO]" if result.get(
            'is_auto_generated_channel') else ""
        if result.get('is_auto_generated_channel'):
            oac_count += 1

        if result['has_spotify']:
            spotify_found += 1
            print(f"✅ Spotify: {result['spotify_links']}{oac_tag}")
        else:
            print(f"— sem Spotify ({len(result['links'])} links){oac_tag}")

        scraped += 1
        if i < total - 1:
            time.sleep(delay)

    # Salva cache
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)

    print(
        f"\n✅ Scraping concluído: {scraped} novos + {total - scraped} do cache")
    print(f"✅ Artistas com Spotify no perfil: {spotify_found}/{total}")
    print(f"⚠️  Canais auto-gerados (OAC): {oac_count}/{total}")
    print(f"✅ Cache salvo em: {output_file}")

    return cache


def load_cached_channel_links(cache_file="data/raw/channel_links_scraped.json"):
    """Carrega links já scrapeados do cache."""
    if not os.path.exists(cache_file):
        return {}
    with open(cache_file, 'r', encoding='utf-8') as f:
        return json.load(f)


if __name__ == "__main__":
    import sys

    # Carrega artistas → channel_ids do JSONL
    artists_channels = {}
    with open("data/raw/youtube_videos_raw.jsonl", 'r', encoding='utf-8') as f:
        for line in f:
            v = json.loads(line)
            a = v.get('artist_name')
            c = v.get('channel_id')
            if a and c and a not in artists_channels:
                artists_channels[a] = c

    force = '--force' in sys.argv
    scrape_all_channels(artists_channels, force=force)
